services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: dawapp
    container_name: dawapp-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - dawapp

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: dawapp-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: entrenamientos
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: entrenamientos_user
      MYSQL_PASSWORD: daw2025
    networks:
      - dawapp

  nginx:
    image: nginx:1.17-alpine
    platform: linux/amd64
    container_name: dawapp-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - dawapp

networks:
  dawapp:
    driver: bridge
